DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS inventory;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  jumps INTEGER NOT NULL,
  currency INTEGER NOT NULL,
  tries DECIMAL(10, 1) NOT NULL
);

CREATE TABLE inventory (
  user_id VARCHAR(100) NOT NULL,
  item_id VARCHAR(100) NOT NULL,
  PRIMARY KEY (user_id, item_id)
);